name: ev_charging_stations_locator_fyp
description: "A charging stations locator app for electric vehicles (EVs) in Nepal."
publish_to: 'none' # This line prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.0
  flutter_map: ^6.1.0
  geolocator: ^11.0.0
  flutter_polyline_points: ^2.0.0
  permission_handler: ^11.3.0
  provider: ^6.1.2
  dynamic_color: ^1.7.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # Optional: adds recommended lints for better coding practices

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data.json # Add the JSON file to assets
